---
- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Define mariadb_logbase_dir
  set_fact:
    mariadb_logbase_dir: "{{ __mariadb_logbase_dir }}"
  when: mariadb_logbase_dir is not defined

- name: Define mariadb_logbase_dir_owner
  set_fact:
    mariadb_logbase_dir_owner: "{{ __mariadb_logbase_dir_owner }}"
  when: mariadb_logbase_dir_owner is not defined

- name: Define mariadb_logbase_dir_group
  set_fact:
    mariadb_logbase_dir_group: "{{ __mariadb_logbase_dir_group }}"
  when: mariadb_logbase_dir_group is not defined

- name: Define mariadb_logbase_dir_mode
  set_fact:
    mariadb_logbase_dir_mode: "{{ __mariadb_logbase_dir_mode }}"
  when: mariadb_logbase_dir_mode is not defined

- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Check if Mariadb packages were installed.
  set_fact:
    mariadb_install_packages: "{{ (rh_mariadb_install_packages is defined and rh_mariadb_install_packages.changed)
      or (deb_mariadb_install_packages is defined and deb_mariadb_install_packages.changed) }}"

- include: configure-server.yml

- include: secure-installation.yml
  when: skip_secure_installation is undefined

- include: databases.yml
  when: (mariadb_databases | default([])) | length

- include: users.yml
  when: (mariadb_users | default([])) | length
