---
- name: Enable MariaDB yum repository | RedHat
  template:
    src: MariaDB.repo.j2
    dest: /etc/yum.repos.d/MariaDB.repo
    owner: root
    group: root
    mode: 0644

- name: Import MariaDB GPG key | Redhat
  rpm_key:
    key: '{{ mariadb_rpm_gpg_key }}'
    state: present

- name: Ensure MariaDB packages are installed | Redhat
  package:
    name: '{{ item }}'
    state: present
  with_items: '{{ mariadb_packages }}'
  register: rh_mariadb_install_packages