---
- name: Import MariaDB GPG keys | Debian / Ubuntu
  apt_key:
    keyserver: 'keyserver.ubuntu.com'
    id: '{{ item }}'
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  with_items: '{{ mariadb_apt_gpg_keys }}'

- name: Enable MariaDB apt repository | Debian / Ubuntu
  apt_repository:
    repo: 'deb {{ mariadb_apt_mirror_base }}/{{ mariadb_version }}/{{ ansible_distribution|lower }}/ {{ ansible_distribution_release }} main'
    state: present
    update_cache: yes

- name: Ensure MariaDB packages are installed | Debian / Ubuntu
  package:
    name: '{{ item }}'
    state: present
  with_items: '{{ mariadb_packages }}'
  register: deb_mariadb_install_packages