---
- name: Enable MariaDB yum repository | RedHat
  template:
    src: MariaDB.repo.j2
    dest: /etc/yum.repos.d/MariaDB.repo
    owner: root
    group: root
    mode: 0644

- name: Import MariaDB GPG key | Redhat
  rpm_key:
    key: '{{ mariadb_rpm_gpg_key }}'
    state: present

- name: Ensure MariaDB-client is installed | Redhat
  yum:
    name: '{{ mariadb_client_package }}'
    state: installed
  when: 'mariadb_install_client == True'

- name: Ensure MariaDB-server is installed | Redhat
  yum:
    name: '{{ mariadb_server_package }}'
    state: installed
  when: 'mariadb_install_server == True'
