---
- name: Restart MariaDB
  service:
    name: '{{ mariadb_service_name }}'
    state: restarted

- name: Restart MariaDB immediatly
  service:
    name: '{{ mariadb_service_name }}'
    state: restarted
