---
- hosts: all

  vars:
    mariadb_version: 10.5
    mariadb_fetch_wsrep_status: true
    mariadb_bind_address: '0.0.0.0'
    mariadb_mysqld_options:
      'max_connections': '50'
      '#comment':

    mariadb_galera_role: primary
    mariadb_galera_primary: localhost
    mariadb_databases:
      - name: somedb
    mariadb_users:
      - name: someuser
        host: "%"
        password: somepassword
        priv: "somedb.*:ALL"

  pre_tasks:
    - name: Ensure GnuPG is installed on Debian 9 (Stretch)
      package:
        name: gnupg
        state: present
      changed_when: false
      when: ansible_distribution_release == 'stretch'

    - name: Ensure apt-utils is installed on Ubuntu | Debian / Ubuntu
      package:
        name: apt-utils
        state: present
      changed_when: false
      when: ansible_os_family == 'Debian'

  roles:
    - role: jgeusebroek.mariadb
