---
- hosts: all

  tasks:
    - name: Install required packages (Debian / Ubuntu)
      apt:
        update_cache: yes
        name: ['gnupg']
        state: present
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
